cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/ndnops/ndn-ops/NOC/nfdDataCollection/.waf-1.8.0-094bcb3e7079041614f60222067e94d3/waflib/Tools/c_config.py", line 478, in run_c_code\n    bld.compile()\n  File "/home/ndnops/ndn-ops/NOC/nfdDataCollection/.waf-1.8.0-094bcb3e7079041614f60222067e94d3/waflib/Build.py", line 182, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 28092944: cxx test.cpp -> test.cpp.1.o}\n[\'/usr/bin/g++\', \'-Werror\', \'-std=c++11\', \'../test.cpp\', \'-c\', \'-o\', \'/home/ndnops/ndn-ops/NOC/nfdDataCollection/build/.conf_check_b150c0600ccd48f9dd5ae13ba2d58321/testbuild/test.cpp.1.o\']\n'
